version: '3.7'

services:

    binance_bot:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        stdin_open: true
        tty: true
        container_name: binance_bot
        environment:
            - BINANCE_API_KEY=SECRET
            - BINANCE_API_SECRET=SECRET
            - BINANCE_HTTP_URI=https://testnet.binance.vision/api
            - BINANCE_WS_URI=wss://testnet.binance.vision/ws
            - TELEGRAM_API=SECRET
        volumes:
            - ./:/app
            - binance_bot_dist:/app/dist
            - binance_bot_node_modules:/app/node_modules
        ports:
            - 8080:8080
            - 9229:9229

volumes:
    binance_bot_node_modules:
    binance_bot_dist:
networks:
    default:
        name: binance_bot-environment-network
